// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



//Function that creates an array of fib numbers with upper limit specified by user
//max n is 573147844013817200000

function fibArrayCreator(n){

  let fibArray = [1];
  var a = 0;
  var b = 1;
  var temp;

  for(i=0;i<100;i++){
    temp = a + b;
    a = b;
    b = temp;

    if(temp>n){
      break;
    }

    fibArray.push(temp);
  }

  return fibArray;
}

//function that sums even numbers in an Array

function sumEvens(arr){
  var sum = 0;
  for(i=0;i<=arr.length;i++){
    if(arr[i]%2==0){
      sum+=arr[i];
    }
  }
  return sum;
}



console.log(sumEvens(fibArrayCreator(40000000)));
